# This is a basic workflow to help you get started with Actions

name: eneskirimi.com-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      ENESKIRIMI_KEY: ${{ secrets.ENESKIRIMI_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WEBSITE_PATH: ${{ secrets.WEBSITE_PATH }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: |
          cd eneskirimi.com-webpack-setup
          npm install
          
    - name: Run build command
      run: |
          cd eneskirimi.com-webpack-setup
          npm run build
          
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
          # Private Key
        key: ${{ env.ENESKIRIMI_KEY }}
        port: 2222
          # Remote host
        host: ${{ env.SSH_HOST }}
          # Remote user
        username: ${{ env.SSH_USER }}
          # Source directory
        source: eneskirimi.com-webpack-setup/dist
          # Target directory
        target: ${{ env.WEBSITE_PATH }}
